#!/bin/bash

# Based on boot-arm64
#
# Do install stuff for riscv64, including making bootable CDs
# Works with debian-installer
#
# $1 is the CD number
# $2 is the temporary CD build dir
#

. $BASEDIR/tools/boot/$DI_CODENAME/common.sh

set -e
#set -x

N=$1
CDDIR=$2
INSTALLDIR="install"

# Common options for all disks
add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-J -joliet-long"
add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-cache-inodes"
add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-l"

# Exit if this is not CD#1/DVD#1
if [ $N != "1" ]; then
    exit 0
fi

if [ "$DI_WWW_HOME" = "default" ]; then
    DI_WWW_HOME="https://d-i.debian.org/daily-images/riscv64/daily"
    try_di_image_cache
else
    DI_WWW_HOME=$(echo $DI_WWW_HOME | sed "s,%ARCH%,$ARCH,")
fi

case "$MKISOFS" in
    *xorriso*)
        XORRISO_VER=$(xorriso_version)
        ;;
    *)
        echo "ERROR: debian-cd depends on xorriso for making $ARCH bootable CDs."
        exit 1;
        ;;
esac

cd $CDDIR/..

BOOT_IMAGES="cdrom/initrd.gz cdrom/vmlinux cdrom/debian-cd_info.tar.gz"

# Download boot images.
for image in $BOOT_IMAGES; do
    if [ ! -e "$image" ]; then
        dir=$(dirname $image)
        mkdir -p $dir
        if [ -n "$LOCAL"  -a -f "${LOCALDEBS:-$MIRROR}/dists/$DI_DIST/local/installer-$ARCH/current/images/$image" ]; then
            cp "${LOCALDEBS:-$MIRROR}/dists/$DI_DIST/local/installer-$ARCH/current/images/$image" "$image"
        elif [ ! "$DI_WWW_HOME" ];then
            if [ ! "$DI_DIR" ];then
                DI_DIR="$MIRROR/dists/$DI_DIST/main/installer-$ARCH/current/images"
            fi
            cp "$DI_DIR/$image" "$image"
        else
            $WGET "$DI_WWW_HOME/$image" -O "$image"
        fi
    fi
done

mkdir -p $CDDIR/$INSTALLDIR
cp -lf cdrom/vmlinux $CDDIR/$INSTALLDIR/
cp -lf cdrom/initrd.gz $CDDIR/$INSTALLDIR/

# Boot setup including config and help files comes from d-i.
mkdir -pv $PWD/boot$N
cat cdrom/debian-cd_info.tar.gz | (cd boot$N/; tar zx)

if [ -d boot$N/grub ] ; then
    echo "  Adding EFI boot code for $ARCH on CD$N"

    # Extract DTB files
    mkdir -p $CDDIR/dtb
    mcopy -n -s -i boot$N/grub/efi.img '::dtb/*' $CDDIR/dtb

    # Extract GRUB files
    mkdir -p $CDDIR/EFI/boot
    mcopy -n -s -i boot$N/grub/efi.img '::efi/*' $CDDIR/EFI
    mkdir -p $CDDIR/boot/grub
    mv boot$N/grub/* $CDDIR/boot/grub/
    rmdir boot$N/grub

    # Do not repack efi.img, the version provided by d-i is suitable to create a bootable CD

    # Location of the EFI boot image, and don't emulate a floppy or HD
    add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-e boot/grub/efi.img -no-emul-boot"

    # Add an *extra* partition on the end for the EFI bits
    add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-append_partition 2 0xef $CDDIR/boot/grub/efi.img"

    # And force alignment
    add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-partition_cyl_align all"

    # Finally, belt and braces - fix up the %install% entries in grub
    # in case they're still there
    sed -i "s|\%install\%|$INSTALLDIR|g" $CDDIR/boot/grub/grub.cfg

    # Substitute custom KERNEL_PARAMS into grub.cfg
    sed -i "s|/vmlinux |/vmlinux $KERNEL_PARAMS |g" $CDDIR/boot/grub/grub.cfg

else
    echo "  No EFI boot code for $ARCH on CD$N"
fi

# th,th, thats all
